# Generated by Django 3.1.7 on 2021-07-27 12:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('spa', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='features',
            name='title',
            field=models.CharField(default=1, max_length=50),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='house',
            name='slug',
            field=models.SlugField(default=1, unique=True),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='house',
            name='name',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='style',
            name='description',
            field=models.TextField(),
        ),
    ]
