# Generated by Django 3.1.7 on 2021-07-28 13:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('spa', '0005_remove_house_slug'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='house',
            name='photo',
        ),
        migrations.CreateModel(
            name='Photo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('main_photo', models.BooleanField()),
                ('photo', models.ImageField(upload_to='')),
                ('house', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='spa.house')),
            ],
        ),
    ]
