# Generated by Django 3.1.7 on 2021-07-28 17:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('spa', '0006_auto_20210728_1747'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='photo',
            name='main_photo',
        ),
    ]
