# Generated by Django 3.1.7 on 2021-07-28 18:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('spa', '0008_auto_20210728_2140'),
    ]

    operations = [
        migrations.AddField(
            model_name='house',
            name='price',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
    ]
